branches:
  only:
  - master

arch:
  - amd64

os: linux

dist: bionic

env:
  - REPONAME=$(basename $TRAVIS_REPO_SLUG) ALARCH=x86_64

language: generic

addons:
  apt:
    packages:
      - libarchive-tools
      - zstd

git:
  quiet: true

cache:
  directories:
    - $HOME/cache
    - $HOME/src

before_script:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git --branch gh-pages --single-branch $HOME/repo || true
  - rm -f -r $HOME/repo/.git

script:
  - sudo ./mkrepo.sh $USER $TRAVIS_BUILD_DIR $ALARCH

before_deploy:
  - sudo chown -R $USER:$USER $HOME/repo
  - ./createlinks.sh $HOME/repo $REPONAME
  - ./genindex.sh $HOME/repo $REPONAME

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: $HOME/repo/
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: master
