name: AUR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  main:
    name: Build & Release
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
          sudo apt-get update
          sudo apt-get -y install libarchive-tools zstd
          git clone --depth 1 --branch gh-pages $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git $HOME/repo || true

      - name: Build artifacts
        env:
          ALARCH: x86_64
        run: |
          sudo $GITHUB_WORKSPACE/mkrepo.sh $USER $GITHUB_WORKSPACE $ALARCH
          REPONAME=$(basename $GITHUB_REPOSITORY)
          sudo chown -R $USER $HOME/repo
          ./createlinks.sh $HOME/repo $REPONAME
          ./genindex.sh $HOME/repo $REPONAME

      - name: Publish built artifacts
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $HOME/repo
          git update-ref -d HEAD
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Publish $GITHUB_REPOSITORY/$GITHUB_RUN_ID/$GITHUB_RUN_NUMBER"
          git push -f "https://$GITHUB_REPOSITORY_OWNER:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" gh-pages
