# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create: { }
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Prepare and run build
        env:
          ALARCH: x86_64
        run: |
          sudo apt-get update
          sudo apt-get -y install libarchive-tools zstd
          id
          pwd
          ls -l
          printenv | sort
          sudo $GITHUB_WORKSPACE/mkrepo.sh $USER $GITHUB_WORKSPACE $ALARCH
